### PR TITLE
support custome import path go.etcd.io/raft

### PR DESCRIPTION
**Pull request by ahrtr**
Signed-off-by: Benjamin Wang <wachao@vmware.com>

cc @philips @spzala

### CODE REVIEW

**Comment by philips** [comment]
LGTM

**Comment by ahrtr** [comment]
Thanks  @philips for the quick review. 

Could you please grant write or admin permission to me on this repo?

**Comment by philips** [comment]
maintainers-etcd should have admin access now. Odd that they don't have admin access to all repos...

**Comment by ahrtr** [comment]
> maintainers-etcd should have admin access now. Odd that they don't have admin access to all repos...

Thank you @philips

**Comment by spzala** [comment]
@ahrtr glad that it worked out. @philips thank you so much!

**Pull request merged**
